name: upload new container

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update legacy version
        run: |
          sed -E -i "s/(LEGACY_VERSION = \")(v[0-9.]+)(\")/\1v${{ github.event.release.tag_name }}\3/" src/edge.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automated legacy version update"
          git push origin HEAD:master

  docker:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/edgegpt-telegram-bot:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
